### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by yegor256** [yegor256/loog#75]
```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
	/app/vendor/bundle/ruby/3.2.0/gems/loog-0.5.2/lib/loog.rb:108:in `join'
	/app/vendor/bundle/ruby/3.2.0/gems/loog-0.5.2/lib/loog.rb:108:in `to_s'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.3`
